### ISSUE TITLE
pygatt.util.lescan() missing attribute

### ISSUE THREAD

**Issue by STFURTFMLAGG** [linklayer/BLEKey#4]
[n/c] blekey> scan
scanning...
Traceback (most recent call last):
  File "blekey.py", line 138, in <module>
    BLEKeyClient().cmdloop()
  File "/usr/lib64/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "blekey.py", line 28, in do_scan
    scan_result = pygatt.util.lescan()
AttributeError: 'module' object has no attribute 'lescan'

**Comment by blark** [comment]
Can you see if using this Pygatt fixes it? 

https://github.com/blark/pygatt.git

**EDIT**

Actually it looks like pip is just installing the wrong pygatt. I forked the one at https://github.com/ampledata/pygatt and that one definitely still has lescan. That one should work too and is still maintained. 

You should be able to install with:

```
git clone https://github.com/ampledata/pygatt.git pygatt
cd pygatt
python setup.py install
```

Let me know if anything else explodes. ;)

Thanks.

**Comment by STFURTFMLAGG** [comment]
It fixes the missing attribute, but I had a new explosion:

n/c] blekey> scan
scanning...
Traceback (most recent call last):
  File "blekey.py", line 138, in <module>
    BLEKeyClient().cmdloop()
  File "/usr/lib64/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "blekey.py", line 28, in do_scan
    scan_result = pygatt.util.lescan()
  File "/usr/lib64/python2.7/site-packages/pygatt-1.3.0-py2.7.egg/pygatt/util.py", line 53, in lescan
    scan.expect('foooooo', timeout=timeout)
  File "/usr/lib64/python2.7/site-packages/pexpect/**init**.py", line 1451, in expect
    timeout, searchwindowsize)
  File "/usr/lib64/python2.7/site-packages/pexpect/**init**.py", line 1466, in expect_list
    timeout, searchwindowsize)
  File "/usr/lib64/python2.7/site-packages/pexpect/**init**.py", line 1554, in expect_loop
    raise EOF(str(err) + '\n' + str(self))
pexpect.EOF: End Of File (EOF). Exception style platform.
<pexpect.spawn object at 0x7f30b042f490>
version: 3.3
command: /usr/bin/sudo
args: ['/usr/bin/sudo', 'hcitool', 'lescan']
searcher: <pexpect.searcher_re object at 0x7f30b042f4d0>
buffer (last 100 chars): ''
before (last 100 chars): 'Set scan parameters failed: Input/output error\r\n'
after: <class 'pexpect.EOF'>
match: None
match_index: None
exitstatus: 1
flag_eof: True
pid: 5333
child_fd: 3
closed: False
timeout: 30
delimiter: <class 'pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1

**Comment by blark** [comment]
A couple of questions:
- What platform are you on? 
- Are you running the tool as root? BLE tools require it. 
- What BLE adapter are you using? 
- What is the output of `hciconfig`?

Note if you are on Mac bluetooth sharing through VMware does not work. You need to turn off your bluetooth adapter and connect it manually to Linux.

**Comment by nhasler** [comment]
ubuntu 15.1 VM and pentoo VM
Running python as root, yes.
Macbook pro internal adapter shared with VM

hci0:Type: BR/EDR  Bus: USB
BD Address: AC:BC:32:A0:F4:13  ACL MTU: 8192:128  SCO MTU: 64:128
UP RUNNING
RX bytes: 533 acl:0 sco:0 events:27 errors:0
TX bytes: 609 acl:0 sco:0 commands:27 errors:0

**Comment by Choongkyu** [comment]
not sure if this thread is hard-closed but I've been having the same exact issues on Arch Linux 4.8.13-1, while running BLE tools as root, with BLE v1.2 and the output to hciconfig is as follows:
```

hci0:	Type: Primary  Bus: USB
	BD Address: 68:94:23:E9:AE:0A  ACL MTU: 1021:8  SCO MTU: 64:1
	DOWN 
	RX bytes:882 acl:0 sco:0 events:36 errors:0
	TX bytes:386 acl:0 sco:0 commands:36 errors:0
```

I had run pip uninstall pygatt, installed your forked version of pygatt using the steps above and then tried to run blekey.py, with the following results:
```
Traceback (most recent call last):
  File "blekey.py", line 3, in <module>
    import pygatt
  File "/usr/lib/python3.5/site-packages/pygatt-1.3.0-py3.5.egg/pygatt/__init__.py", line 20, in <module>
    from .classes import BluetoothLEDevice
  File "/usr/lib/python3.5/site-packages/pygatt-1.3.0-py3.5.egg/pygatt/classes.py", line 16, in <module>
    import thread
ImportError: No module named 'thread'
```
I tried then to install the thread module with "sudo pip install thread" and got the following:

```
Collecting thread
  Could not find a version that satisfies the requirement thread (from versions: )
No matching distribution found for thread
```
EDIT:

I just went over to http://stackoverflow.com/questions/3326740/pydev-importerror-no-module-named-thread-debugging-no-longer-works-after-pydev#3353841 and edited File "/usr/lib/python3.5/site-packages/pygatt-1.3.0-py3.5.egg/pygatt/classes.py", line 16, in <module>
    import thread

to read
```
try:    
    import thread 
except ImportError:
    import _thread as thread
```
And BLE tools is now running, but when trying to scan, I get: 
```
scanning...
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pexpect/spawnbase.py", line 150, in read_nonblocking
    s = os.read(self.child_fd, size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/lib/python3.5/site-packages/pexpect/pty_spawn.py", line 465, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/lib/python3.5/site-packages/pexpect/spawnbase.py", line 155, in read_nonblocking
    raise EOF('End Of File (EOF). Exception style platform.')
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "blekey.py", line 138, in <module>
    BLEKeyClient().cmdloop()
  File "/usr/lib/python3.5/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.5/cmd.py", line 217, in onecmd
    return func(arg)
  File "blekey.py", line 28, in do_scan
    scan_result = pygatt.util.lescan()
  File "/usr/lib/python3.5/site-packages/pygatt-1.3.0-py3.5.egg/pygatt/util.py", line 53, in lescan
    scan.expect('foooooo', timeout=timeout)
  File "/usr/lib/python3.5/site-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/usr/lib/python3.5/site-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python3.5/site-packages/pexpect/expect.py", line 105, in expect_loop
    return self.eof(e)
  File "/usr/lib/python3.5/site-packages/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7efc170852b0>
command: /usr/bin/sudo
args: ['/usr/bin/sudo', 'hcitool', 'lescan']
buffer (last 100 chars): b''
before (last 100 chars): b'Could not open device: No such device\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 10301
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("b'foooooo'")
```

Any help would be much appreciated.  Cheers and happy new year!
